language: node_js
node_js:
  - '6'
  - '4'
matrix:
  include:
  - node_js: 7
    env:
      - secure: K06xord93jGaSu0PKgPwHyZJrD5hBkdh+vpUJFHNFLK61dlU8ZyBWkfIGEMdz7do8GE+wd3lXRLG4I9ib7ZOv4A5pablJ1lXch80fh9auKIrXjUWUsk+a/NVsHAgAFn4sHIHf/tGLPTXIAwj1AStxQcGsGl9iD83T89+9XEVFLMKDct0u7eJpwD3zQmEsO0dr1QOZ6QQ3LJpIlSEluuQwlOm8W00gRTLCWuhTm8c/WNTNSHsBuSDmHiZfs/VJ80EXFHD7YzIlVyiNz+4IysBXwhYzOa4eh+FSX157ESMc56DlfPNYvN930hViB0zI4H7IFekOLzu9COoBT+1WFb0XHxK3kqOabPc9u2sNrWSUtWdDKuQVuHH+9tTc/b92YB3raBEExdRR4ZiugqXgWE4BMrQys/zYW6cPPBuZbUhX2+/VaLxq9rc4wt5cOmnGzAL6qn4516Pj+5qpQmGooB9eH4mKHTnHbWcKj4Z9g/ctyX3CxdLnYvNp3JeaXH9GAHd58WcQcvxM4EleY+Sc0ieHpy68nMUHqQzGBxX07uBKgNHcvAtqGlP4QxsaZBK2uLI+HwhM8kdsOg31lJOIMVlNp8sE09SUNRgqwUNDPkSzDEIRSmwvGGtlDMYdBj8y6+/lSFOcdpTaVBKB+p0T968fE1qqdDG45ZpBK5bHzl9WWg=
sudo: false
git:
  depth: 5
cache:
  directories:
    - ~/.npm
before_install:
  - npm config set spin false --global
