language: node_js
node_js:
- '6'
- '4'
matrix:
  include:
  - node_js: 7
    env:
    - secure: WeaXYaXxi9kMqypUOgbFtbt7kLk4ojf+Jk2cZqAFwtdMiwk2TysD+fckPn6qpBQzwxcj1XdfYNiY72pHe+BEFxThNQ3LM/Lz60M6ZCkJCkJ2LpQDOtGISQAV+a/4ZVvL2ENRg6V/JvXvUV5jlk8e9flwW06hh20JOzGIX0D9Ez8WIy439vjsUv6Umywh6jXR9VdzouRgWb1sQ2q71JYghaa8Ny+HNtEYbTC3JmFVZ8PdMmqpKLbX5axTGGH9DBkRYSoDBmaoOZqv2ppscTTr/vbr9PqbkWMo78jlH5ly35QBfttuV8xgi6dIq+N6AX0CIAfG1dzjsjqC2hbWDrErbVn4Og+DNUC7o201JAZOzYrCv4fc7kGjsfsTjeUMQG9JRvdsAzoJxnCnr7AiXYgMcipAaNnLPflF9tIfHb48PB5nk3NGc4S2CwIiE1rQI3LOOaCvy0bWLyptMF4FxH1D6yiyXvQoHpnZ92zCFyVPJ+HB+giuUjOrma0Qc2Pwm8Mch7GdCa86UJPA/dcbKu2xBK2YJf/QmVHnI0XvI6M+an9kg9wUtRr3WnNnM4r4DMvl4CiX6eVCdGk5jPfAXaZgBOuN/HIT6xZGZOZRCflHcqrfD/eYTaNOb1TjSO5eelFc/nlk5FKX2DDsmevvu1M8ND++DsxbHZPWtPHZHANlgnk=
sudo: false
git:
  depth: 5
cache:
  directories:
  - ~/.npm
before_install:
- npm config set spin false --global
env:
  global:
    secure: gYcC87R/PY4LWrfQQ6Vflv/4tHvqepVCJ83gIEyw6ruXqMbVzMjYWlCoccLzIHSI+1um+rNkZrWwlm3fsExWNnRKoyM+Veuj18XpTw4cseQja/OkDew7qgRRAuS75DmkHruWO+I2Ffltc21zBxRsVt8CuMmOwSQg0bsITk0V8FT2rsyX1mNd0WWchQ5Tw/hCcYR0wnk9lw1U5uQ2V2DGbU/WvLLpWmyW4vRmasAjvyhN/w7ryoAVqpVSlTOf14KtGPAy8WWghFJJm6kt4wwHx/3rFDIO+mHZXuyURfZ9Ip6o4XbwIjL+QJGDtqOYen1rOxf+DZteiCuPXG/YCX8uKiQutehn5iLRjRFvAkLoRsx1dPQPssMg94ouTWyaDbD5YGTSrgChjiHobzVDBaluScW5NW9f9mgjaqtYI/Th5oKEpW/8hyK6+OaEYDSpEl3C1Zy4AFPwp8j9O2K6Ig87YXRwR8XSyO9oMf5d+ml+Z/bNxcUOClzFb67p5o2JuZfl7/nTyj6lsG38gNYcbtVeIndv8djn/ixi5ssrL4X9X4FdRKqA4OYqT6u9+Irqolea2js94K6dCaDS9Oc074esbcrGbz0vdl2O8LTKBzK+uqhKEO+WY7r4kpYkgqBfydRpbueGhGItzbehJu7DgrMeJv3UUAht12ZWo5aXlMpGMmE=
